Vou 28
VOU-jcxdc/vou-app pull request #5
Opened 2024-08-20 13:49 UTC by MinEn1712

- Complete events and favorite events flow
- Update profile avatar has some issues :")

2024-08-21 01:05 UTC, vmathu commented on app/(tabs)/(events)/index.tsx
> +
k phải giữ để check sau thì xoá nha m

2024-08-21 01:05 UTC, vmathu commented on app/(tabs)/(events)/event-details/[id].tsx
> +
hmmm t thí cái này có dùng lại, tạo global để dùng lại hem, bỏ ở đâu thì ch bik 🐧

2024-08-21 15:40 UTC, MinEn1712 commented on app/(tabs)/(favorite-events)/index.tsx
> +          // ListFooterComponent={<View>{isFetchingNextPage && <ActivityIndicator />}</View>}
ye cái này t đang tính gắn infinity scroll cho Favorite Events lun á nhma nó đang nhập nhằng một số thứ, nên là chắc cứ để vậy uy

2024-08-21 15:41 UTC, MinEn1712 commented on app/(tabs)/(events)/index.tsx
> +
này cũng xài lun nhen mà chắc t quên sửa lại huheo 🥹

2024-08-23 00:37 UTC, vmathu requested changes

2024-08-23 00:37 UTC, vmathu commented on app/(tabs)/(events)/index.tsx
> +            </Pressable>
ủa s k để pressable trong event card nựa á m

2024-08-23 00:37 UTC, vmathu commented on lib/api/api.ts
> +  });
tạo `doPutImage` hay j đó k m, í là k bik có cách nào extend từ `doPut` kia hay là truyền thêm `Content-Type` vào k á, tại t thí import thêm axios ở đây thì kì

2024-08-23 00:37 UTC, vmathu commented on package.json
package nào k dùng thì uninstall nha

2024-08-23 01:41 UTC, MinEn1712 commented on app/(tabs)/(events)/index.tsx
> +            </Pressable>
cái này do vụ path á :")) cái pathname nó phải là cái path do expo router nó quy định nên là nó hong đc là biến lun, nên hong truyền qua props đc :")))))))) nên là để ngoài thì trang event để path event, trang fav event để path fav event

2024-08-23 02:30 UTC, merged